"""Reproduce Figure 7 from the shipped 10-seed loss arrays.

The NPZ was generated by ``experiments/plot_best_config_curves.py`` using
hidden width 64, learning rate 0.05, 200 training samples, 50 validation
samples, 3,000 epochs, and 10 seeds. This plotting-only script does not
retrain or overwrite the authoritative arrays.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parent
RELEASE_ROOT = ROOT.parent
INPUT_PATH = (
    RELEASE_ROOT / "experiments" / "results" /
    "best_config_gap_filling_curves.npz"
)
FIGURE_DIR = ROOT / "outputs" / "figures"
RESULT_DIR = ROOT / "outputs" / "results"

ORDER = ["CauchyNet", "NBeats", "FNN_ReLU", "SIREN"]
COLORS = {"CauchyNet": "#e66101", "SIREN": "#1f78b4",
          "FNN_ReLU": "#33a02c", "NBeats": "#6a3d9a"}
LABELS = {"CauchyNet": "CauchyNet", "SIREN": "SIREN",
          "FNN_ReLU": "FNN (ReLU)", "NBeats": "N-BEATS"}


def main() -> None:
    curves = np.load(INPUT_PATH)
    expected_shapes = {
        f"{model}_{split}": (10, 3000)
        for model in ORDER for split in ("train", "val")
    }
    for key, expected in expected_shapes.items():
        if key not in curves or curves[key].shape != expected:
            raise ValueError(f"{key}: expected {expected}, got {getattr(curves.get(key), 'shape', None)}")

    plt.rcParams.update({
        "font.size": 11, "axes.labelsize": 12, "axes.titlesize": 13,
        "legend.fontsize": 10, "xtick.labelsize": 10, "ytick.labelsize": 10,
        "pdf.fonttype": 42, "ps.fonttype": 42,
    })
    figure, axes = plt.subplots(1, 2, figsize=(11, 4.5), sharey=True)
    for model in ORDER:
        epoch = np.arange(1, 3001)
        for axis, split in zip(axes, ("train", "val")):
            values = curves[f"{model}_{split}"]
            mean, standard_deviation = values.mean(axis=0), values.std(axis=0)
            axis.plot(epoch, mean, label=LABELS[model], color=COLORS[model], linewidth=1.6)
            axis.fill_between(epoch, np.maximum(mean - standard_deviation, 1e-9),
                              mean + standard_deviation, color=COLORS[model],
                              alpha=0.15, linewidth=0)

    for axis, title in zip(axes, ("Training loss (MSE)", "Validation loss (MSE)")):
        axis.set_yscale("log")
        axis.set_xlabel("Epoch")
        axis.set_title(title)
        axis.grid(True, which="both", alpha=0.25)
    axes[0].set_ylabel("Loss")
    axes[0].legend(loc="upper right", frameon=True, framealpha=0.9)
    figure.suptitle(
        r"Gap-filling loss curves at best config ($h{=}64$, lr$=0.05$, "
        r"$n_{\mathrm{train}}{=}200$, 3000 epochs, 10 seeds, $\pm 1\sigma$)",
        fontsize=12, y=1.02,
    )
    figure.tight_layout()

    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    stem = FIGURE_DIR / "figure07_gap_filling_curves"
    figure.savefig(stem.with_suffix(".pdf"), bbox_inches="tight")
    figure.savefig(stem.with_suffix(".png"), dpi=200, bbox_inches="tight")
    plt.close(figure)

    result_path = RESULT_DIR / "figure07_gap_filling_curves.json"
    result_path.write_text(json.dumps({
        "input": str(INPUT_PATH.relative_to(RELEASE_ROOT)),
        "input_sha256": hashlib.sha256(INPUT_PATH.read_bytes()).hexdigest(),
        "shape_per_model_and_split": [10, 3000],
        "config": {"hidden_size": 64, "learning_rate": 0.05,
                   "train_points": 200, "validation_points": 50,
                   "epochs": 3000, "seeds": 10},
    }, indent=2) + "\n")
    print(f"Saved {stem.with_suffix('.pdf')}")
    print(f"Saved {stem.with_suffix('.png')}")
    print(f"Saved {result_path}")


if __name__ == "__main__":
    main()
